apiVersion: v1
kind: Service
metadata:
  name: grpc-example
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: http2
  selector:
    app: grpc-example
  type: LoadBalancer